"""
Django settings for django_api_exp project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import cv2
import torch
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'api_exp',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_api_exp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_api_exp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'testDB',
        'USER': 'hogehoge',
        'PASSWORD': 'password',
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'UTC'

USE_I18N = True

TIME_ZONE = 'Asia/Tokyo'

device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')

# YOLO_MODEL = torch.hub.load('ultralytics/yolov5', 'custom', path='/code/static/model/asahuka96hozon.pt')
# YOLO_MODEL = torch.hub.load('ultralytics/yolov5', 'custom', path='/code/static/model/yolov5s_800best.pt')
YOLO_MODEL = torch.hub.load('ultralytics/yolov5', 'custom', path='/code/static/model/holeplus.pt')
YOLO_MODEL.to(device)
YOLO_MODEL.conf = 0.25  # NMS confidence threshold
YOLO_MODEL.iou = 0.45  # NMS IoU threshold
YOLO_MODEL.agnostic = False  # NMS class-agnostic
YOLO_MODEL.multi_label = False  # NMS multiple labels per box
YOLO_MODEL.classes = None  # (optional list) filter by class, i.e. = [0, 15, 16] for COCO persons, cats and dogs
YOLO_MODEL.max_det = 1000  # maximum number of detections per image
YOLO_MODEL.amp = False  # Automatic Mixed Precision (AMP) inference

UPP_MODEL = torch.load('/code/static/model/best_model_quita_600.pth')
CAOD_MODEL = torch.hub.load('ultralytics/yolov5', 'custom', path='/code/static/model/OOD_v1_100clust.pt')
CAOD_MODEL.to(device)
CAOD_MODEL.conf = 0.1  # NMS confidence threshold
CAOD_MODEL.iou = 0.1  # NMS IoU threshold
CAOD_MODEL.agnostic = True  # NMS class-agnostic
CAOD_MODEL.multi_label = False  # NMS multiple labels per box
CAOD_MODEL.classes = None  # (optional list) filter by class, i.e. = [0, 15, 16] for COCO persons, cats and dogs
CAOD_MODEL.max_det = 1000  # maximum number of detections per image
CAOD_MODEL.amp = False  # Automatic Mixed Precision (AMP) inference

YOLO_TO_REMOVE_MODEL = torch.hub.load('ultralytics/yolov5', 'yolov5s')
YOLO_TO_REMOVE_MODEL.to(device)
YOLO_TO_REMOVE_MODEL.conf = 0.4  # NMS confidence threshold
YOLO_TO_REMOVE_MODEL.iou = 0.4  # NMS IoU threshold

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATIC_URL = 'static/'
print(STATIC_ROOT)
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
